// Build helpers:
//   node tools/build.mjs          -> app/js/samples.js + dist/phil-iri-recorder.html (one offline file)
//   node tools/build.mjs --body   -> also dist/artifact.html (page body only, for web preview hosting)
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const app = path.join(root, 'app');
const dist = path.join(root, 'dist');
fs.mkdirSync(dist, { recursive: true });

// 1. embed the sample templates so the app can load them without files
const samples = {
  GST: { name: 'GST class profile (already filled)', file: 'sample-template-GST-filled.xlsx' },
  A: { name: 'Class reading summary (blank)', file: 'sample-template-A.xlsx' },
};
let js = '/* Generated by tools/build.mjs from samples/*.xlsx - do not edit. */\nwindow.SAMPLE_TEMPLATES = {\n';
for (const [k, s] of Object.entries(samples)) {
  const b64 = fs.readFileSync(path.join(root, 'samples', s.file)).toString('base64');
  js += `  ${k}: { name: ${JSON.stringify(s.name)}, file: ${JSON.stringify(s.file)}, data: '${b64}' },\n`;
}
js += '};\n';
fs.writeFileSync(path.join(app, 'js', 'samples.js'), js);

// 2. inline css + scripts into one html file
let html = fs.readFileSync(path.join(app, 'index.html'), 'utf8');
html = html.replace(/<link rel="stylesheet" href="styles\.css">/, () => `<style>\n${fs.readFileSync(path.join(app, 'styles.css'), 'utf8')}\n</style>`);
html = html.replace(/<script src="([^"]+)"><\/script>/g, (all, src) => {
  const code = fs.readFileSync(path.join(app, src), 'utf8').replace(/<\/script/gi, '<\\/script');
  return `<script>\n${code}\n</script>`;
});
fs.writeFileSync(path.join(dist, 'phil-iri-recorder.html'), html);

if (process.argv.includes('--body')) {
  // the artifact host adds its own doctype/head/body; keep title, fonts, style and content
  const head = /<head>([\s\S]*?)<\/head>/.exec(html)[1].replace(/<meta charset="utf-8">\s*/, '').replace(/<meta name="viewport"[^>]*>\s*/, '');
  const body = /<body>([\s\S]*)<\/body>/.exec(html)[1];
  fs.writeFileSync(path.join(dist, 'artifact.html'), head.trim() + '\n' + body.trim() + '\n');
}
console.log('built', fs.readdirSync(dist).join(', '));
